### ISSUE TITLE
Jhome.java:82-85: The javac binary might not be available...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/jhome#10]
The puzzle `5-ee2a7bdc` from #5 has to be resolved: 

https://github.com/yegor256/jhome/blob/2268a06bdb739258ad1aee0adcf543e79c057d7d/src/main/java/com/yegor256/Jhome.java#L82-L85

The puzzle was created by @volodya-lombrozo on 22-Nov-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by volodya-lombrozo** [comment]
@yegor256 Maybe we should just thrown an exception, if `javac` is absent on the current system. What do you think?

**Comment by volodya-lombrozo** [comment]
btw, I can solve this issue

**Comment by yegor256** [comment]
@volodya-lombrozo yes, throwing an exception seems to be the right solution. Please, go ahead.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`
